import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NRI",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
  showHeader = true,
  showFooter = true,
}: Readonly<{
  children: React.ReactNode;
  showHeader?: boolean;
  showFooter?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        {children}
     <Footer />
      </body>
    </html>
  );
}
