import type { Metadata } from "next";
import "./globals.css";
import ConditionalWrapper from "@/components/root";
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "NRI",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Inter:400,500&display=swap"
          rel="stylesheet"
        />
      </head>

      <body style={{ fontFamily: "'Inter', serif" }}>
      <Suspense fallback={<div>Loading...</div>}>
        <ConditionalWrapper
          routeName={[
            "/signup",
            "/signin",
            "/verify",
            "/verify-pan",
            "/verify-pan2",
            "/skip",
            "/profile",
          ]}
        >
          {children}
        </ConditionalWrapper>
</Suspense>
      </body>
    </html>
  );
}
